/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CareerRouteImport } from './routes/career'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerIndexRouteImport } from './routes/career.index'
import { Route as InternalSlugRouteImport } from './routes/internal.$slug'
import { Route as CareerResultsRouteImport } from './routes/career.results'
import { Route as CareerResetPasswordRouteImport } from './routes/career.reset-password'
import { Route as CareerMatchRouteImport } from './routes/career.match'
import { Route as CareerDashboardRouteImport } from './routes/career.dashboard'
import { Route as CareerAuthRouteImport } from './routes/career.auth'
import { Route as CareerAssessmentRiasecRouteImport } from './routes/career.assessment.riasec'
import { Route as CareerAssessmentBigfiveRouteImport } from './routes/career.assessment.bigfive'

const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerRoute,
} as any)
const InternalSlugRoute = InternalSlugRouteImport.update({
  id: '/internal/$slug',
  path: '/internal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerResultsRoute = CareerResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CareerRoute,
} as any)
const CareerResetPasswordRoute = CareerResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => CareerRoute,
} as any)
const CareerMatchRoute = CareerMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => CareerRoute,
} as any)
const CareerDashboardRoute = CareerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CareerRoute,
} as any)
const CareerAuthRoute = CareerAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => CareerRoute,
} as any)
const CareerAssessmentRiasecRoute = CareerAssessmentRiasecRouteImport.update({
  id: '/assessment/riasec',
  path: '/assessment/riasec',
  getParentRoute: () => CareerRoute,
} as any)
const CareerAssessmentBigfiveRoute = CareerAssessmentBigfiveRouteImport.update({
  id: '/assessment/bigfive',
  path: '/assessment/bigfive',
  getParentRoute: () => CareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/career/auth': typeof CareerAuthRoute
  '/career/dashboard': typeof CareerDashboardRoute
  '/career/match': typeof CareerMatchRoute
  '/career/reset-password': typeof CareerResetPasswordRoute
  '/career/results': typeof CareerResultsRoute
  '/internal/$slug': typeof InternalSlugRoute
  '/career/': typeof CareerIndexRoute
  '/career/assessment/bigfive': typeof CareerAssessmentBigfiveRoute
  '/career/assessment/riasec': typeof CareerAssessmentRiasecRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career/auth': typeof CareerAuthRoute
  '/career/dashboard': typeof CareerDashboardRoute
  '/career/match': typeof CareerMatchRoute
  '/career/reset-password': typeof CareerResetPasswordRoute
  '/career/results': typeof CareerResultsRoute
  '/internal/$slug': typeof InternalSlugRoute
  '/career': typeof CareerIndexRoute
  '/career/assessment/bigfive': typeof CareerAssessmentBigfiveRoute
  '/career/assessment/riasec': typeof CareerAssessmentRiasecRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/career/auth': typeof CareerAuthRoute
  '/career/dashboard': typeof CareerDashboardRoute
  '/career/match': typeof CareerMatchRoute
  '/career/reset-password': typeof CareerResetPasswordRoute
  '/career/results': typeof CareerResultsRoute
  '/internal/$slug': typeof InternalSlugRoute
  '/career/': typeof CareerIndexRoute
  '/career/assessment/bigfive': typeof CareerAssessmentBigfiveRoute
  '/career/assessment/riasec': typeof CareerAssessmentRiasecRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/career/auth'
    | '/career/dashboard'
    | '/career/match'
    | '/career/reset-password'
    | '/career/results'
    | '/internal/$slug'
    | '/career/'
    | '/career/assessment/bigfive'
    | '/career/assessment/riasec'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career/auth'
    | '/career/dashboard'
    | '/career/match'
    | '/career/reset-password'
    | '/career/results'
    | '/internal/$slug'
    | '/career'
    | '/career/assessment/bigfive'
    | '/career/assessment/riasec'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/career/auth'
    | '/career/dashboard'
    | '/career/match'
    | '/career/reset-password'
    | '/career/results'
    | '/internal/$slug'
    | '/career/'
    | '/career/assessment/bigfive'
    | '/career/assessment/riasec'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRouteWithChildren
  InternalSlugRoute: typeof InternalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/': {
      id: '/career/'
      path: '/'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof CareerRoute
    }
    '/internal/$slug': {
      id: '/internal/$slug'
      path: '/internal/$slug'
      fullPath: '/internal/$slug'
      preLoaderRoute: typeof InternalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/results': {
      id: '/career/results'
      path: '/results'
      fullPath: '/career/results'
      preLoaderRoute: typeof CareerResultsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/reset-password': {
      id: '/career/reset-password'
      path: '/reset-password'
      fullPath: '/career/reset-password'
      preLoaderRoute: typeof CareerResetPasswordRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/match': {
      id: '/career/match'
      path: '/match'
      fullPath: '/career/match'
      preLoaderRoute: typeof CareerMatchRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/dashboard': {
      id: '/career/dashboard'
      path: '/dashboard'
      fullPath: '/career/dashboard'
      preLoaderRoute: typeof CareerDashboardRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/auth': {
      id: '/career/auth'
      path: '/auth'
      fullPath: '/career/auth'
      preLoaderRoute: typeof CareerAuthRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/assessment/riasec': {
      id: '/career/assessment/riasec'
      path: '/assessment/riasec'
      fullPath: '/career/assessment/riasec'
      preLoaderRoute: typeof CareerAssessmentRiasecRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/assessment/bigfive': {
      id: '/career/assessment/bigfive'
      path: '/assessment/bigfive'
      fullPath: '/career/assessment/bigfive'
      preLoaderRoute: typeof CareerAssessmentBigfiveRouteImport
      parentRoute: typeof CareerRoute
    }
  }
}

interface CareerRouteChildren {
  CareerAuthRoute: typeof CareerAuthRoute
  CareerDashboardRoute: typeof CareerDashboardRoute
  CareerMatchRoute: typeof CareerMatchRoute
  CareerResetPasswordRoute: typeof CareerResetPasswordRoute
  CareerResultsRoute: typeof CareerResultsRoute
  CareerIndexRoute: typeof CareerIndexRoute
  CareerAssessmentBigfiveRoute: typeof CareerAssessmentBigfiveRoute
  CareerAssessmentRiasecRoute: typeof CareerAssessmentRiasecRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerAuthRoute: CareerAuthRoute,
  CareerDashboardRoute: CareerDashboardRoute,
  CareerMatchRoute: CareerMatchRoute,
  CareerResetPasswordRoute: CareerResetPasswordRoute,
  CareerResultsRoute: CareerResultsRoute,
  CareerIndexRoute: CareerIndexRoute,
  CareerAssessmentBigfiveRoute: CareerAssessmentBigfiveRoute,
  CareerAssessmentRiasecRoute: CareerAssessmentRiasecRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRouteWithChildren,
  InternalSlugRoute: InternalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
